import DS from 'ember-data';

export default DS.Model.extend({
  bornOn: DS.attr('string'),
  ssn: DS.attr('string'),
  driversLicenseNumber: DS.attr('string'),
  driversLicenseState: DS.attr('string'),
  phoneNumber: DS.attr('string'),
  bankName: DS.attr('string'),
  bankCityAndState: DS.attr('string'),
  petsDescription: DS.attr('string'),
  vehiclesDescription: DS.attr('string'),
  wasEverEvicted: DS.attr('string'),
  wasEverEvictedExplanation: DS.attr('string'),
  isFelon: DS.attr('string'),
  isFelonExplanation: DS.attr('string'),
  characterReferenceName: DS.attr('string'),
  characterReferenceContactInfo: DS.attr('string'),
  emergencyContactName: DS.attr('string'),
  emergencyContactPhoneNumber: DS.attr('string'),
  currentHomeStreetAddress: DS.attr('string'),
  currentHomeMovedInOn: DS.attr('string'),
  currentHomeDissatisfactionExplanation: DS.attr('string'),
  currentHomeOwner: DS.attr('string'),
  currentHomeOwnerContactInfo: DS.attr('string'),
  previousHomeStreetAddress: DS.attr('string'),
  previousHomeMovedInOn: DS.attr('string'),
  previousHomeMovedOut: DS.attr('string'),
  previousHomeDissatisfactionExplanation: DS.attr('string'),
  previousHomeOwner: DS.attr('string'),
  previousHomeOwnerContactInfo: DS.attr('string'),
  employmentStatus: DS.attr('string'),
  currentEmploymentPosition: DS.attr('string'),
  currentEmploymentMonthlyIncome: DS.attr('string'),
  currentEmploymentSupervisor: DS.attr('string'),
  currentEmploymentEmployer: DS.attr('string'),
  currentEmploymentEmployerPhoneNumber: DS.attr('string'),
  currentEmploymentEmployerEmailAddress: DS.attr('string'),
  currentEmploymentStartedOn: DS.attr('string'),
  previousEmploymentPosition: DS.attr('string'),
  previousEmploymentMonthlyIncome: DS.attr('string'),
  previousEmploymentSupervisor: DS.attr('string'),
  previousEmploymentEmployer: DS.attr('string'),
  previousEmploymentEmployerPhoneNumber: DS.attr('string'),
  previousEmploymentEmployerEmailAddress: DS.attr('string'),
  previousEmploymentStartedOn: DS.attr('string'),
  previousEmploymentEndedOn: DS.attr('string'),
  otherIncomeMonthlyAmount: DS.attr('string'),
  otherIncomeSources: DS.attr('string'),
  cosignerName: DS.attr('string'),
  cosignerEmailAddress: DS.attr('string'),
  desiresToMoveInOn: DS.attr('string'),
  roommatesDescription: DS.attr('string'),
  victigOrderId: DS.attr('string'),
  victigUrl: DS.attr('string'),
  applicant: DS.belongsTo('applicant', {async: true}),
  coSigner: DS.belongsTo('co-signer', {async: true})
});
